version: '3.3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
#    volumes:
#      - "./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"
    ports:
      - 5601:5601
    networks: 
      - elastic-stack
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    expose:
      - 9300
    networks:
      - elastic-stack
    volumes:
      - es-data:/usr/share/elasticsearch/data
  logstach:
    image: docker.elastic.co/logstash/logstash:7.3.0
    volumes:
      - "./pipeline/:/usr/share/logstash/pipeline/"
    networks:
      - elastic-stack
volumes:
  es-data:
    driver: local
networks:
  elastic-stack:

